
services:
  # 1. API Servisi (Bizim FastAPI kodumuz)
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app # Görev 0.3'te güncellenmişti (TÜM PROJEYİ bağla)
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - minio
    networks: # <-- YENİ
      - notes-net

  # 2. Veritabanı Servisi (PostgreSQL)
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks: # <-- YENİ
      - notes-net

  # 3. Cache & Kuyruk Servisi (Redis)
  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks: # <-- YENİ
      - notes-net

  # 4. S3 Depolama Servisi (MinIO)
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    networks: # <-- YENİ
      - notes-net

  # 5. MinIO Bucket Oluşturucu Servis
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    volumes:
      - ./scripts:/scripts
    entrypoint: /scripts/create-buckets.sh
    networks: # <-- YENİ
      - notes-net

  # 6. Arka Plan İşlemcisi (RQ Worker)
  rq-worker:
    build: .
    command: rq worker default high
    env_file:
      - .env
    depends_on:
      - redis
      - api
    networks: # <-- YENİ
      - notes-net

# Docker'ın verileri saklayacağı kalıcı disk alanları (Volume'ler)
volumes:
  postgres_data:
  redis_data:
  minio_data:

# ---- YENİ BLOK ----
# Tüm servislerimizin bağlanacağı özel bir ağ tanımlıyoruz
networks:
  notes-net:
    driver: bridge